notion :
  token : &token 'here is your own notion intergration token'  # Obtain your own token from notion intergration: https://www.notion.so/my-integrations/
  api_version : &version '2022-06-28'  # API version
  header : # Requests header information
    Authorization : !join ['Bearer ', *token]  # The !join constructor needs to be added in python
    Notion-Version : *version 
    Content-Type : 'application/json'
tasks :
  - 
    run : True
    name : task_1 # Custom name for differentiation of output file
    describe : Thinking in the past year from the Memo database # Description of the current task, used to record what the task is to do
    database_id : 'here is your database id for analysis' # database id
    extra : # Options for filtering and sorting the database
      filter :
        and :
          - 
            property : Label
            multi_select :
              contains : Thinking
          - 
            timestamp : &time_key last_edited_time # created_time is also available
            *time_key : 
              past_year : {} # past_week, past_month, past_year
              # on_or_after: '2021-05-10'
  - 
    run : True
    name : task_2 # Custom name for differentiation of output file
    describe : Summary from the Memo database # Description of the current task, used to record what the task is to do
    database_id : 'here is your database id for analysis' # database id
    extra : # Options for filtering and sorting the database
      filter :
        and :
          - 
            or:
              - 
                property : Label
                multi_select : 
                  contains : summary
              - 
                property : Label
                multi_select : 
                  contains : efficency
          - 
            property : Label
            multi_select :
              does_not_contain : personal
